### ISSUE TITLE
Use CircleCI to run tests

### ISSUE THREAD

**Issue by k4m4** [unmock/micro-jaymock#7]
- Create a [`.circleci/config.yml`](https://circleci.com/docs/2.0/configuration-reference/) file to run the `test.js` file and perform coverage tests.
- Helpful documentation: [`circleci.com/docs/2.0/language-javascript/`](https://circleci.com/docs/2.0/language-javascript/)
- You can also refer to [`unmock/unmock-js/.circleci/config.yml`](https://github.com/unmock/unmock-js/blob/dev/.circleci/config.yml).

**Comment by surajrockzz** [comment]
can I work on this
